version: '3.3'
services:

  app:
    image: wordpress
    ports:
      - 80:80

  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    volumes:
      - db-data:/var/lib/mysql

  db-client:
    image: phpmyadmin
    ports:
      - 81:80

  mailserver:
    image: axllent/mailpit
    ports:
      - 8025:8025
      - 1025:1025

volumes:
  db-data: